version: '2.2'
services:
  elasticsearch:
    build: es
    container_name: elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./es/config/user_dict.csv:/usr/share/elasticsearch/config/user_dict.csv
    ports:
      - 9200:9200
    expose:
      - 9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  kibana:
    build: kibana
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
volumes:
    es-data:
        driver: local
networks:
  esnet:
